"use client"

import { useEffect, useState } from "react"
import { useParams, useNavigate } from "react-router-dom"
import { useAuth } from "../context/AuthContext"
import { db } from "../config/firebase"
import { doc, getDoc } from "firebase/firestore"
import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"
import logoUrl from "/logo-image.png"

export default function AnalysisDetail() {
  const { id } = useParams()
  const { user } = useAuth()
  const navigate = useNavigate()
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    if (!user) {
      navigate("/")
      return
    }

    const fetchData = async () => {
      try {
        const ref = doc(db, "users", user.uid, "history", id)
        const snap = await getDoc(ref)
        if (snap.exists()) setData({ id: snap.id, ...snap.data() })
        else setError("Analysis not found.")
      } catch (err) {
        setError("Failed to fetch analysis.")
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [user, id, navigate])

  const fmtDate = (v) => (v?.toDate ? v.toDate().toLocaleString() : new Date(v).toLocaleString())

  const exportPDF = async () => {
    if (!data) return
    const docPDF = new jsPDF({ unit: "pt", format: "a4" })
    const res = await fetch(logoUrl)
    const blob = await res.blob()
    const reader = new FileReader()
    const imgData = await new Promise((resolve) => {
      reader.onloadend = () => resolve(reader.result)
      reader.readAsDataURL(blob)
    })

    docPDF.addImage(imgData, "PNG", 40, 30, 64, 64)
    docPDF.setFontSize(18).text("Credify AI — Detailed Analysis Report", 120, 60)
    docPDF.setFontSize(11).text(`Date: ${fmtDate(data.date)}`, 40, 110)
    docPDF.text(`Analysis ID: ${data.id}`, 40, 128)

    autoTable(docPDF, {
      head: [["Field", "Value"]],
      body: [
        ["Original Text / URL", data.text || ""],
        ["Summary", data.summary || ""],
        ["Full Analysis", data.analysis || ""],
        ["Score", data.score ?? ""],
        ["Verdict", data.verdict || ""],
        ["Category", data.category || ""],
      ],
      startY: 150,
      styles: { fontSize: 11, cellPadding: 6, overflow: "linebreak" },
      headStyles: { fillColor: [16, 233, 86] },
    })

    docPDF.text("Generated by Credify AI", 40, docPDF.internal.pageSize.height - 40)
    docPDF.save(`credify-detailed-report-${data.id}.pdf`)
  }

  if (loading) return <div className="min-h-screen text-white flex items-center justify-center">Loading...</div>
  if (error) return <div className="min-h-screen text-white flex items-center justify-center">{error}</div>

  return (
    <div className="min-h-screen bg-gray-900 text-white px-4 py-6">
      <div className="max-w-4xl mx-auto bg-gray-800 rounded-xl shadow-lg p-6 border border-gray-700">
        <h1 className="text-2xl font-bold mb-4">Detailed Analysis</h1>
        <p className="text-sm text-gray-400 mb-6">ID: {data.id} | {fmtDate(data.date)}</p>

        <div className="space-y-6">
          <div>
            <h2 className="font-semibold">Original Content</h2>
            <p className="text-gray-300 whitespace-pre-wrap">{data.text}</p>
          </div>

          <div className="bg-gray-700 rounded-lg p-4">
            <h2 className="font-semibold mb-2">Summary</h2>
            <p>{data.summary}</p>
          </div>

          {data.analysis && (
            <div>
              <h2 className="font-semibold">Full Analysis</h2>
              <p className="text-gray-300 whitespace-pre-wrap">{data.analysis}</p>
            </div>
          )}

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6">
            <div className="bg-gray-700 p-4 rounded-lg text-center">
              <p className="text-sm text-gray-400">Score</p>
              <p className="text-xl font-bold">{data.score ?? "-"}</p>
            </div>
            <div className="bg-gray-700 p-4 rounded-lg text-center">
              <p className="text-sm text-gray-400">Verdict</p>
              <p className={`text-xl font-bold ${data.verdict === "Credible" ? "text-green-400" : "text-red-400"}`}>
                {data.verdict}
              </p>
            </div>
            <div className="bg-gray-700 p-4 rounded-lg text-center">
              <p className="text-sm text-gray-400">Category</p>
              <p className="text-xl font-bold">{data.category || "-"}</p>
            </div>
            <div className="bg-gray-700 p-4 rounded-lg text-center">
              <p className="text-sm text-gray-400">Date</p>
              <p>{fmtDate(data.date)}</p>
            </div>
          </div>
        </div>

        <div className="mt-6 flex flex-wrap gap-3">
          <button onClick={exportPDF} className="bg-[#10e956] text-black px-4 py-2 rounded-lg">Export PDF</button>
          <button onClick={() => navigate("/analyze", { state: { text: data.text } })} className="bg-gray-700 px-4 py-2 rounded-lg">Re-analyze</button>
          <button onClick={() => navigate("/history")} className="bg-gray-700 px-4 py-2 rounded-lg">Back</button>
        </div>
      </div>
    </div>
  )
}
