"use client"

import { useEffect, useState } from "react"
import { motion } from "framer-motion"
import { Search, Bell, Home, FileSearch, History as HistoryIcon, Settings, Menu, Download, RefreshCw, Eye } from "lucide-react"
import { useNavigate } from "react-router-dom"
import { useAuth } from "../context/AuthContext"
import { db, auth } from "../config/firebase"
import { collection, query, orderBy, getDocs } from "firebase/firestore"
import { signOut } from "firebase/auth"
import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"
import logoUrl from "/logo-image.png"

export default function History() {
  const { user, loading: authLoading } = useAuth()
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [isSidebarOpen, setIsSidebarOpen] = useState(false)
  const [firstName, setFirstName] = useState("")
  const navigate = useNavigate()

  // Set firstName when user is loaded
  useEffect(() => {
    if (user === undefined) return
    if (!user) {
      navigate("/")
    } else {
      if (user.displayName) {
        setFirstName(user.displayName.split(" ")[0])
      } else if (user.email) {
        setFirstName(user.email.split("@")[0])
      }
    }
  }, [user, navigate])

  useEffect(() => {
    if (authLoading) return
    if (!user) {
      setItems([])
      setLoading(false)
      return
    }

    const fetchHistory = async () => {
      setLoading(true)
      try {
        const histColl = collection(db, "users", user.uid, "history")
        const q = query(histColl, orderBy("date", "desc"))
        const snap = await getDocs(q)
        const data = snap.docs.map((d) => ({ id: d.id, ...d.data() }))
        setItems(data)
      } catch (err) {
        console.error("Error loading history:", err)
        setError("Failed to load history.")
      } finally {
        setLoading(false)
      }
    }

    fetchHistory()
  }, [user, authLoading])

  const fmtDate = (v) => {
    if (!v) return ""
    if (v.toDate) return v.toDate().toLocaleString()
    return new Date(v).toLocaleString()
  }

  const exportPDF = async (item) => {
    try {
      const doc = new jsPDF({ unit: "pt", format: "a4" })
      const res = await fetch(logoUrl)
      const blob = await res.blob()
      const reader = new FileReader()
      const imgData = await new Promise((resolve) => {
        reader.onloadend = () => resolve(reader.result)
        reader.readAsDataURL(blob)
      })

      doc.addImage(imgData, "PNG", 40, 30, 64, 64)
      doc.setFontSize(18).text("Credify AI — Content Analysis Report", 120, 60)
      doc.setFontSize(11).text(`Date: ${fmtDate(item.date)}`, 40, 110)
      doc.text(`Analysis ID: ${item.id}`, 40, 128)

      autoTable(doc, {
        head: [["Field", "Value"]],
        body: [
          ["Original Text / URL", item.text || ""],
          ["Summary", item.summary || ""],
          ["Score", item.score ?? "-"],
          ["Verdict", item.verdict || ""],
          ["Category", item.category || ""],
        ],
        startY: 150,
        styles: { fontSize: 11, cellPadding: 6 },
        headStyles: { fillColor: [16, 233, 86] },
      })

      doc.text("Generated by Credify AI", 40, doc.internal.pageSize.height - 40)
      doc.save(`credify-report-${item.id}.pdf`)
    } catch (err) {
      console.error("Export PDF failed:", err)
    }
  }

  const handleViewFull = (id) => navigate(`/analysis/${id}`)
  const handleReanalyze = (text) => navigate("/analyze", { state: { text } })
  const handleLogout = async () => {
    await signOut(auth)
    navigate("/")
  }
  const toggleSidebar = () => setIsSidebarOpen(!isSidebarOpen)

  const sidebarItems = [
    { icon: Home, label: "Overview", path: "/dashboard" },
    { icon: FileSearch, label: "Analyze Content", path: "/analyze" },
    { icon: HistoryIcon, label: "History", path: "/history" },
    { icon: Settings, label: "Settings", path: "/settings" },
  ]

  if (authLoading || user === undefined) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-900 text-white">
        <p>Loading...</p>
      </div>
    )
  }

  if (!user) return null

  return (
    <div className="min-h-screen bg-gray-900 text-white flex flex-col lg:flex-row">
      {/* Mobile Header */}
      <div className="lg:hidden flex items-center justify-between px-4 py-3 bg-gray-900 fixed top-0 left-0 right-0 z-50">
        <button onClick={toggleSidebar} className="text-white focus:outline-none">
          <Menu className="w-6 h-6" />
        </button>
        <span className="text-xl font-bold text-white">Credify AI</span>
        <div className="w-8 h-8 bg-[#10e956] rounded-full flex items-center justify-center font-bold text-black text-sm">
          {firstName?.charAt(0).toUpperCase()}
        </div>
      </div>

      {/* Sidebar */}
      <motion.aside
        className={`fixed lg:static top-0 inset-y-0 left-0 z-40 w-64 bg-gray-800 transform transition-transform duration-300 ease-in-out ${
          isSidebarOpen ? "translate-x-0" : "-translate-x-full lg:translate-x-0"
        }`}
        initial={false}
      >
        <div className="flex flex-col h-full pt-16 lg:pt-0">
          <div className="flex items-center gap-3 p-6 border-b border-gray-700">
            <div className="w-8 h-8 flex items-center justify-center">
              <img
                src="/logo-image.png"
                alt="Credify AI Logo"
                className="w-8 h-8 object-contain rounded-full"
              />
            </div>
            <span className="text-xl font-bold">Credify AI</span>
          </div>

          <nav className="flex-1 p-4">
            <ul className="space-y-2">
              {sidebarItems.map((item) => {
                const IconComp = item.icon
                return (
                  <li key={item.label}>
                    <button
                      onClick={() => {
                        navigate(item.path)
                        setIsSidebarOpen(false)
                      }}
                      className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-200 ${
                        window.location.pathname === item.path
                          ? "bg-[#10e956]/20 text-[#10e956] border border-[#10e956]/30"
                          : "text-gray-400 hover:text-white hover:bg-gray-700"
                      }`}
                    >
                      <IconComp className="w-5 h-5" />
                      <span className="font-medium">{item.label}</span>
                    </button>
                  </li>
                )
              })}
            </ul>
          </nav>
        </div>
      </motion.aside>

      {isSidebarOpen && <div className="fixed inset-0 bg-black/50 z-30 lg:hidden" onClick={toggleSidebar} />}

      {/* Main Content */}
      <div className="flex-1 flex flex-col min-w-0 pt-[64px] lg:pt-0">
        {/* Desktop Header */}
        <header className="bg-gray-800 border-b border-gray-700 px-4 lg:px-6 py-4 hidden lg:block">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search..."
                  className="bg-gray-700 border border-gray-600 rounded-lg pl-10 pr-4 py-2 text-sm focus:outline-none focus:border-[#10e956] focus:ring-2 focus:ring-[#10e956]/20 w-64 lg:w-80"
                />
              </div>
            </div>
            <div className="flex items-center gap-4">
              <button className="relative p-2 rounded-lg hover:bg-gray-700">
                <Bell className="w-5 h-5" />
                <span className="absolute -top-1 -right-1 w-3 h-3 bg-red-500 rounded-full"></span>
              </button>
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 bg-[#10e956] rounded-full flex items-center justify-center font-bold text-black text-sm">
                  {firstName?.charAt(0).toUpperCase()}
                </div>
                <span className="hidden sm:block font-medium capitalize">{firstName}</span>
                <button
                  onClick={handleLogout}
                  className="ml-2 px-4 py-1 bg-gray-700 text-white text-sm rounded hover:bg-red-500 transition"
                >
                  Logout
                </button>
              </div>
            </div>
          </div>
        </header>

        {/* Content */}
        <main className="flex-1 px-4 lg:px-6 pt-6 pb-6 overflow-auto">
          <div className="max-w-7xl mx-auto">
            <div className="mb-6">
              <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold">Analysis History</h1>
              <p className="text-sm sm:text-base text-gray-400 mt-1">View and manage your past content analyses</p>
            </div>

            {loading ? (
              <div className="flex justify-center items-center py-20">
                <div className="w-10 h-10 border-4 border-[#10e956] border-t-transparent rounded-full animate-spin" />
              </div>
            ) : error ? (
              <p className="text-red-400 text-sm sm:text-base">{error}</p>
            ) : items.length === 0 ? (
              <div className="text-center py-20">
                <HistoryIcon className="w-16 h-16 text-gray-600 mx-auto mb-4" />
                <p className="text-gray-400 text-sm sm:text-base">No history yet. Run an analysis to get started.</p>
                <button
                  onClick={() => navigate("/analyze")}
                  className="mt-4 px-6 py-2 bg-[#10e956] text-black rounded-lg hover:bg-[#0ef052] transition"
                >
                  Analyze Content
                </button>
              </div>
            ) : (
              <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
                {items.map((it) => (
                  <div key={it.id} className="bg-gray-800 rounded-lg p-4 border border-gray-700 flex flex-col min-w-0">
                    <div className="mb-3">
                      <h2 className="font-semibold text-[#10e956] text-sm sm:text-base line-clamp-2 break-words">
                        {it.text?.slice(0, 80) || "Untitled"}
                      </h2>
                      <p className="text-xs sm:text-sm text-gray-400 mt-2 line-clamp-2 break-words">
                        {it.summary?.slice(0, 120) || "No summary available"}
                      </p>
                    </div>

                    <div className="mt-auto">
                      <div className="flex items-center justify-between mb-3 text-xs sm:text-sm">
                        <div>
                          <p className="text-gray-400">Score</p>
                          <p className="font-bold text-white">{it.score ?? "-"}%</p>
                        </div>
                        <div>
                          <p className="text-gray-400">Verdict</p>
                          <span
                            className={`inline-block px-2 py-1 text-xs rounded-full font-medium ${
                              it.verdict === "Credible" ? "bg-green-600 text-white" : "bg-red-600 text-white"
                            }`}
                          >
                            {it.verdict}
                          </span>
                        </div>
                      </div>

                      <p className="text-xs text-gray-500 mb-3">{fmtDate(it.date)}</p>

                      <div className="grid grid-cols-3 gap-2">
                        <button
                          onClick={() => handleViewFull(it.id)}
                          className="flex items-center justify-center gap-1 bg-gray-700 py-2 px-2 rounded hover:bg-gray-600 transition text-xs"
                          title="View Full"
                        >
                          <Eye className="w-3 h-3" />
                          <span className="hidden sm:inline">View</span>
                        </button>
                        <button
                          onClick={() => handleReanalyze(it.text)}
                          className="flex items-center justify-center gap-1 bg-gray-700 py-2 px-2 rounded hover:bg-gray-600 transition text-xs"
                          title="Re-analyze"
                        >
                          <RefreshCw className="w-3 h-3" />
                          <span className="hidden sm:inline">Re-analyze</span>
                        </button>
                        <button
                          onClick={() => exportPDF(it)}
                          className="flex items-center justify-center gap-1 bg-[#10e956] text-black py-2 px-2 rounded hover:bg-[#0ef052] transition font-medium text-xs"
                          title="Export PDF"
                        >
                          <Download className="w-3 h-3" />
                          <span className="hidden sm:inline">Export</span>
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </main>
      </div>
    </div>
  )
}